RubyOnRails/config/routes.rb
RubyOnRails::Application.routes.draw do
  get 'home/list_all'
  get 'home/show'
  get 'home/show_author'
  get 'home/show_tags'

  resources :post_categories
  resources :categories
  resources :posts

  authenticated :user do
    root :to => 'home#list_all'
  end
  root :to => 'home#list_all'
  devise_for :users
  resources :users
end

RubyOnRails/app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  attr_accessible :category_id, :post_id
end

RubyOnRails/app/controllers/post_categories_controller.rb
class PostCategoriesController < ApplicationController
  # GET /post_categories
  # GET /post_categories.json
  def index
    @post_categories = PostCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @post_categories }
    end
  end

  # GET /post_categories/1
  # GET /post_categories/1.json
  def show
    @post_category = PostCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post_category }
    end
  end

  # GET /post_categories/new
  # GET /post_categories/new.json
  def new
    @post_category = PostCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post_category }
    end
  end

  # GET /post_categories/1/edit
  def edit
    @post_category = PostCategory.find(params[:id])
  end

  # POST /post_categories
  # POST /post_categories.json
  def create
    @post_category = PostCategory.new(params[:post_category])

    respond_to do |format|
      if @post_category.save
        format.html { redirect_to @post_category, notice: 'Post category was successfully created.' }
        format.json { render json: @post_category, status: :created, location: @post_category }
      else
        format.html { render action: "new" }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /post_categories/1
  # PUT /post_categories/1.json
  def update
    @post_category = PostCategory.find(params[:id])

    respond_to do |format|
      if @post_category.update_attributes(params[:post_category])
        format.html { redirect_to @post_category, notice: 'Post category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_categories/1
  # DELETE /post_categories/1.json
  def destroy
    @post_category = PostCategory.find(params[:id])
    @post_category.destroy

    respond_to do |format|
      format.html { redirect_to post_categories_url }
      format.json { head :no_content }
    end
  end
end

RubyOnRails/app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

RubyOnRails/app/views/post_categories/_form.html.erb
<%= simple_form_for(@post_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :post_id %>
    <%= f.input :category_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

RubyOnRails/app/views/post_categories/edit.html.erb
<h1>Editing post_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_category %> |
<%= link_to 'Back', post_categories_path %>

RubyOnRails/app/views/post_categories/index.html.erb
<h1>Listing post_categories</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post_categories.each do |post_category| %>
  <tr>
    <td><%= post_category.post_id %></td>
    <td><%= post_category.category_id %></td>
    <td><%= link_to 'Show', post_category %></td>
    <td><%= link_to 'Edit', edit_post_category_path(post_category) %></td>
    <td><%= link_to 'Destroy', post_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post category', new_post_category_path %>

RubyOnRails/app/views/post_categories/new.html.erb
<h1>New post_category</h1>

<%= render 'form' %>

<%= link_to 'Back', post_categories_path %>

RubyOnRails/app/views/post_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @post_category.post_id %>
</p>

<p>
  <b>Category:</b>
  <%= @post_category.category_id %>
</p>


<%= link_to 'Edit', edit_post_category_path(@post_category) %> |
<%= link_to 'Back', post_categories_path %>